name: OEM GSI Porter

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup ErfanGSIs Tools
        run: |
          sudo apt install p7zip-full p7zip-rar
          wget https://cyfuture.dl.sourceforge.net/project/origin-gsi-tool/2.2.0-sand/ogsitool-release-v2.2.0sand.7z?viasf=1
          7z x ./ogsitool-release-v2.2.0sand.7z
          ls
    
